---
- name: copy calico manifest
  template:
    src: templates/calico.yaml
    dest: /var/lib/rancher/k3s/server/manifests/calico.yaml
  register: calico_manifest

- name: wait for calico-kube-controllers to be Available
  retries: 5
  delay: 10
  shell: kubectl wait --for=condition=Available deployment/calico-kube-controllers -n kube-system
  register: result
  until: result.rc == 0
